import React from 'react';
import './globals.css';
import localFont from '@next/font/local'

const ibmPlexMono = localFont({
  src: [
    {
      path: '../public/IBM_Plex_Mono/IBMPlexMono-Regular.ttf',
      weight: '400'
    },
    {
      path: '../public/IBM_Plex_Mono/IBMPlexMono-ExtraLight.ttf',
      weight: '200'
    }
  ],
  variable: '--font-ibm-plex-mono'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={`${ibmPlexMono.variable} font-mono`}>
      <body>
        {children}
      </body>
    </html>
  );
}
